import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const sourceDir = join(__dirname, "..", "..", "voxelmap-to-image", "out");
const outFile = join(__dirname, "..", "src", "map-data.ts");

const QUADRANT_KEYS = ["pxpy", "nxpy", "pxny", "nxny"];

const entries = QUADRANT_KEYS.map((key) => {
  const pngPath = join(sourceDir, `map-${key}.png`);
  if (!existsSync(pngPath)) return [key, null];

  const png = readFileSync(pngPath);
  // PNG signature (8 bytes) + chunk length (4) + "IHDR" (4) + width (4) + height (4), all big-endian
  const width = png.readUInt32BE(16);
  const height = png.readUInt32BE(20);
  const base64 = png.toString("base64");
  return [key, { width, height, base64 }];
});

const body = entries
  .map(([key, value]) =>
    value
      ? `  ${key}: { width: ${value.width}, height: ${value.height}, dataUrl: "data:image/png;base64,${value.base64}" },`
      : `  ${key}: null,`,
  )
  .join("\n");

writeFileSync(
  outFile,
  `// generated by scripts/embed-map.mjs from ${sourceDir} — do not edit by hand\n` +
    `export interface MapQuadrant {\n  width: number;\n  height: number;\n  dataUrl: string;\n}\n\n` +
    `export const mapQuadrants: Record<"pxpy" | "nxpy" | "pxny" | "nxny", MapQuadrant | null> = {\n${body}\n};\n`,
);

for (const [key, value] of entries) {
  if (value) console.log(`  ${key}: ${value.width}x${value.height}`);
  else console.log(`  ${key}: (none)`);
}
console.log(`wrote ${outFile}`);
