import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const sourcePng = join(__dirname, "..", "..", "voxelmap-to-image", "out", "map.png");
const outFile = join(__dirname, "..", "src", "map-data.ts");

const png = readFileSync(sourcePng);
// PNG signature (8 bytes) + chunk length (4) + "IHDR" (4) + width (4) + height (4), all big-endian
const width = png.readUInt32BE(16);
const height = png.readUInt32BE(20);
const base64 = png.toString("base64");

writeFileSync(
  outFile,
  `// generated by scripts/embed-map.mjs from ${sourcePng} — do not edit by hand\n` +
    `export const mapWidth = ${width};\n` +
    `export const mapHeight = ${height};\n` +
    `export const mapDataUrl = "data:image/png;base64,${base64}";\n`,
);
console.log(`wrote ${outFile} (${width}x${height}, ${(base64.length / 1024).toFixed(0)} KB base64)`);
