import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const sourceDir = join(__dirname, "..", "..", "voxelmap-to-image", "out");
const outFile = join(__dirname, "..", "src", "map-data.ts");

const QUADRANT_KEYS = ["pxpy", "nxpy", "pxny", "nxny"];
// must match voxelmap-to-image's --scale (see render.ts's own MAP_SCALE) —
// used only to derive the heightmap's block dimensions from the image's
const MAP_SCALE = 16;

const entries = QUADRANT_KEYS.map((key) => {
  const pngPath = join(sourceDir, `map-${key}.png`);
  if (!existsSync(pngPath)) return { key, data: null };

  const png = readFileSync(pngPath);
  // PNG signature (8 bytes) + chunk length (4) + "IHDR" (4) + width (4) + height (4), all big-endian
  const width = png.readUInt32BE(16);
  const height = png.readUInt32BE(20);
  const base64 = png.toString("base64");

  const heightsPath = join(sourceDir, `heights-${key}.bin`);
  const heightsBase64 = existsSync(heightsPath) ? readFileSync(heightsPath).toString("base64") : null;
  const heightsWidth = width / MAP_SCALE;
  const heightsHeight = height / MAP_SCALE;

  return { key, data: { width, height, base64, heightsBase64, heightsWidth, heightsHeight } };
});

const body = entries
  .map(({ key, data }) =>
    data
      ? `  ${key}: {\n` +
        `    width: ${data.width},\n` +
        `    height: ${data.height},\n` +
        `    dataUrl: "data:image/png;base64,${data.base64}",\n` +
        `    heightsWidth: ${data.heightsWidth},\n` +
        `    heightsHeight: ${data.heightsHeight},\n` +
        `    heightsBase64: ${data.heightsBase64 ? `"${data.heightsBase64}"` : "null"},\n` +
        `  },`
      : `  ${key}: null,`,
  )
  .join("\n");

writeFileSync(
  outFile,
  `// generated by scripts/embed-map.mjs from ${sourceDir} — do not edit by hand\n` +
    `export interface MapQuadrant {\n` +
    `  width: number;\n` +
    `  height: number;\n` +
    `  dataUrl: string;\n` +
    `  heightsWidth: number;\n` +
    `  heightsHeight: number;\n` +
    `  /** base64 of a little-endian Int16Array, one entry per block, row-major */\n` +
    `  heightsBase64: string | null;\n` +
    `}\n\n` +
    `export const mapQuadrants: Record<"pxpy" | "nxpy" | "pxny" | "nxny", MapQuadrant | null> = {\n${body}\n};\n`,
);

for (const { key, data } of entries) {
  if (data) console.log(`  ${key}: ${data.width}x${data.height} (heights ${data.heightsWidth}x${data.heightsHeight})`);
  else console.log(`  ${key}: (none)`);
}
console.log(`wrote ${outFile}`);
