// Fetches POIs from MongoDB (the admin app's `pois` collection) and bakes them
// into a generated TS file, so the deployed viewer stays a purely static build
// with no runtime database calls.
//
//   MONGODB_URI=... node scripts/fetch-pois.mjs

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { MongoClient } from "mongodb";

const { MONGODB_URI } = process.env;
if (!MONGODB_URI) {
  console.error("missing required env var: MONGODB_URI");
  process.exit(1);
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const outFile = join(__dirname, "..", "src", "poi-data.ts");

const client = new MongoClient(MONGODB_URI);
await client.connect();
const docs = await client.db().collection("pois").find({}).toArray();
await client.close();

const pois = docs.map(({ _id, ...poi }) => poi);

writeFileSync(
  outFile,
  `// generated by scripts/fetch-pois.mjs from the "pois" MongoDB collection — do not edit by hand\n` +
    `import type { PointOfInterest } from "./poi.ts";\n\n` +
    `export const pois: PointOfInterest[] = ${JSON.stringify(pois, null, 2)};\n`,
);
console.log(`wrote ${outFile} (${pois.length} POIs)`);
