// Computes, per chunk, a "how dug is this" percentage and writes it to
// map-render/src/percent-data.ts (consumed by both map views — Leaflet and
// BlueMap). Two interchangeable ways to compute it, picked via --source /
// PERCENT_SOURCE — see percent-sources.ts for what each one actually does
// and why you'd pick one over the other.
//
//   tsx src/index.ts --output <path.ts> [--source voxelmap|wdl] [--input <dir>]
//     [--depth-threshold -58] [--min-y -64] [--max-y 20]
import { writeFileSync } from "node:fs";
import { getPercentSource } from "./percent-sources.ts";

function parseArgs(argv: string[]) {
  const get = (flag: string): string | undefined => {
    const i = argv.indexOf(flag);
    return i === -1 ? undefined : argv[i + 1];
  };

  const source = getPercentSource(get("--source") ?? process.env.PERCENT_SOURCE ?? "voxelmap");
  const input = get("--input") ?? source.defaultInput;
  const output = get("--output");
  if (!output) throw new Error("missing --output <path to write the generated .ts file>");

  const depthThreshold = get("--depth-threshold");
  const minY = get("--min-y");
  const maxY = get("--max-y");

  return {
    source,
    input,
    output,
    depthThreshold: depthThreshold === undefined ? undefined : Number(depthThreshold),
    minY: minY === undefined ? undefined : Number(minY),
    maxY: maxY === undefined ? undefined : Number(maxY),
  };
}

async function main(): Promise<void> {
  const { source, input, output, depthThreshold, minY, maxY } = parseArgs(process.argv.slice(2));
  const results = source.compute({ input, depthThreshold, minY, maxY });

  if (results.length === 0) {
    throw new Error(`no chunks with data found under ${input} (source: ${source.name})`);
  }

  const percents = results.map((r) => r.percent);
  const min = Math.min(...percents);
  const max = Math.max(...percents);
  const avg = percents.reduce((a, b) => a + b, 0) / percents.length;
  console.log(`scanned ${results.length} chunk(s) via "${source.name}": min=${min.toFixed(1)}% max=${max.toFixed(1)}% avg=${avg.toFixed(1)}%`);

  writeFileSync(
    output,
    `// generated by blockdata-scanner — do not edit by hand\n` +
      `import type { ChunkPercent } from "./percent.ts";\n\n` +
      `export const chunkPercents: ChunkPercent[] = ${JSON.stringify(results, null, 2)};\n`,
  );
  console.log(`wrote ${output}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
