// generated by scripts/fetch-pois.mjs from the "pois" MongoDB collection — do not edit by hand
import type { PointOfInterest } from "./poi.ts";

export const pois: PointOfInterest[] = [
  {
    "type": "chunk",
    "x": -16,
    "y": -80,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 16,
    "y": -16,
    "level": "almost"
  },
  {
    "type": "chunk",
    "x": 16,
    "y": 32,
    "level": "almost"
  },
  {
    "type": "chunk",
    "x": 32,
    "y": -32,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 64,
    "y": -64,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 48,
    "y": -16,
    "level": "done"
  },
  {
    "title": "Farm à PDT",
    "description": "On n'en récolte un peu pour les autres et on replante.",
    "x1": 323,
    "y1": 76,
    "x2": 399,
    "y2": 32,
    "color": "green"
  },
  {
    "title": "Outils pour démarrer",
    "color": "gray",
    "type": "startup",
    "x": 12,
    "y": 26
  },
  {
    "title": "Stock à Bonemeal",
    "color": "gray",
    "type": "startup",
    "x": 31,
    "y": -9
  },
  {
    "type": "chunk",
    "x": 32,
    "y": 0,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 16,
    "y": -32,
    "level": "almost"
  },
  {
    "type": "chunk",
    "x": 48,
    "y": -32,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 64,
    "y": -32,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 64,
    "y": -80,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 48,
    "y": 0,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": -16,
    "y": -64,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 64,
    "y": -48,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 64,
    "y": -16,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": -16,
    "y": -48,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 0,
    "y": -32,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 0,
    "y": -16,
    "level": "ongoing"
  },
  {
    "type": "chunk",
    "x": 16,
    "y": 0,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 64,
    "y": 0,
    "level": "done"
  },
  {
    "type": "chunk",
    "x": 32,
    "y": -16,
    "level": "done"
  },
  {
    "title": "Ferme à Bonemeal",
    "color": "gray",
    "type": "startup",
    "x": -3,
    "y": 12
  },
  {
    "title": "Spawn",
    "color": "purple",
    "type": "startup",
    "x": 1,
    "y": 3
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 0,
    "y": -48,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 0,
    "y": -64,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 16,
    "y": -48,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 32,
    "y": -48,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 48,
    "y": -48,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 16,
    "y": -64,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 32,
    "y": -64,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 48,
    "y": -64,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 16,
    "y": 16,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 32,
    "y": 16,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 48,
    "y": 16,
    "level": "done"
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 32,
    "y": 32,
    "level": "done"
  },
  {
    "title": "ch",
    "type": "chunk",
    "x": 48,
    "y": 32,
    "level": "almost"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 64,
    "y": 32,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 64,
    "y": 16,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 48,
    "y": -80,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 32,
    "y": -80,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 16,
    "y": -80,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 0,
    "y": -80,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 80,
    "y": -80,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 80,
    "y": -96,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 64,
    "y": -96,
    "level": "almost"
  },
  {
    "title": "80",
    "type": "chunk",
    "x": 80,
    "y": -64,
    "level": "done"
  },
  {
    "title": "!",
    "type": "chunk",
    "x": 80,
    "y": -48,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 80,
    "y": -32,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 80,
    "y": -16,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 80,
    "y": 0,
    "level": "done"
  },
  {
    "title": "80",
    "type": "chunk",
    "x": 80,
    "y": 16,
    "level": "done"
  },
  {
    "title": "96",
    "type": "chunk",
    "x": 96,
    "y": -32,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 112,
    "y": -32,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 112,
    "y": -16,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 208,
    "y": -48,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 320,
    "y": 320,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 335,
    "y": 351
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 16,
    "y": 128,
    "level": "almost"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 16,
    "y": 144,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": 16,
    "y": 160,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": -32,
    "y": 128,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": -32,
    "y": 144,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": -32,
    "y": 160,
    "level": "done"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": -16,
    "y": 144,
    "level": "almost"
  },
  {
    "title": "c",
    "type": "chunk",
    "x": -16,
    "y": 160,
    "level": "done"
  },
  {
    "title": "Four à Pomme de Terre",
    "color": "pink",
    "x": 316,
    "y": 84
  },
  {
    "title": "Ferme à XP",
    "description": "Ferme à XP au spawn",
    "color": "gray",
    "type": "startup",
    "x": -30,
    "y": 30
  },
  {
    "title": "Lit",
    "color": "yellow",
    "type": "startup",
    "x": 11,
    "y": 11
  },
  {
    "title": "Lit Village",
    "description": "Ne pas détruire",
    "color": "yellow",
    "x": 320,
    "y": 67
  },
  {
    "title": "Arbre",
    "description": "Couper et replanter",
    "color": "green",
    "x": -55,
    "y": -27
  },
  {
    "x": -16,
    "y": -32,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": -128,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 48,
    "y": -112,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 48,
    "y": -96,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 144,
    "y": -64,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 176,
    "y": 80,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 0,
    "y": 160,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 560,
    "y": -64,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 544,
    "y": -48,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 560,
    "y": -48,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 544,
    "y": -32,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 560,
    "y": -32,
    "type": "chunk",
    "level": "done"
  },
  {
    "title": "Lit",
    "color": "yellow",
    "x": 220,
    "y": -28
  },
  {
    "x": -32,
    "y": 176,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": -16,
    "y": 176,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 16,
    "y": -128,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 32,
    "y": -128,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 16,
    "y": -112,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 32,
    "y": -112,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 64,
    "y": -112,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 96,
    "y": -112,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 16,
    "y": -96,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 32,
    "y": -96,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": -96,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": -80,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": -64,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": -48,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 112,
    "y": -48,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 128,
    "y": -48,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 128,
    "y": -32,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 96,
    "y": -16,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 128,
    "y": -16,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": 0,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 112,
    "y": 0,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 128,
    "y": 0,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 160,
    "y": 0,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 96,
    "y": 16,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 80,
    "y": 32,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": 32,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 176,
    "y": 64,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 80,
    "y": 128,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 0,
    "y": 144,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 32,
    "y": 144,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 80,
    "y": 144,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 32,
    "y": 160,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 0,
    "y": 176,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 16,
    "y": 176,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 336,
    "y": 352,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 112,
    "y": -80,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 144,
    "y": -32,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 144,
    "y": 0,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": 112,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": 128,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 112,
    "y": 128,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 96,
    "y": 144,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 80,
    "y": -112,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 144,
    "y": -48,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 144,
    "y": -16,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 160,
    "y": -16,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 112,
    "y": 112,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": -16,
    "y": -96,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 0,
    "y": -128,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 112,
    "y": -64,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 48,
    "y": -144,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 64,
    "y": -144,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 96,
    "y": -144,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 48,
    "y": -128,
    "type": "chunk",
    "level": "ongoing"
  },
  {
    "x": 64,
    "y": -128,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 80,
    "y": -128,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 0,
    "y": -112,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 112,
    "y": -112,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 0,
    "y": -96,
    "type": "chunk",
    "level": "almost"
  },
  {
    "x": 112,
    "y": -96,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 128,
    "y": -96,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 128,
    "y": -80,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 144,
    "y": -80,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 160,
    "y": -80,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 128,
    "y": -64,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 160,
    "y": -64,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 176,
    "y": -64,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 160,
    "y": -48,
    "type": "chunk",
    "level": "ongoing"
  },
  {
    "x": 176,
    "y": -48,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 160,
    "y": -32,
    "type": "chunk",
    "level": "done"
  },
  {
    "x": 176,
    "y": -32,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 80,
    "y": 48,
    "type": "chunk",
    "level": "ongoing"
  },
  {
    "x": 16,
    "y": 80,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 32,
    "y": 80,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 16,
    "y": 96,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 544,
    "y": -64,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": -16,
    "y": -112,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 80,
    "y": -144,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 112,
    "y": -128,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 32,
    "y": 48,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 48,
    "y": 48,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 64,
    "y": 48,
    "type": "chunk",
    "level": "ongoing"
  },
  {
    "x": -16,
    "y": -128,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 16,
    "y": 64,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 32,
    "y": 64,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 48,
    "y": 64,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 64,
    "y": 64,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 80,
    "y": 64,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 48,
    "y": 80,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 64,
    "y": 80,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 80,
    "y": 80,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 32,
    "y": 96,
    "type": "chunk",
    "level": "started"
  },
  {
    "x": 48,
    "y": 96,
    "type": "chunk",
    "level": "started"
  }
];
