// generated by scripts/fetch-pois.mjs from the "pois" MongoDB collection — do not edit by hand
import type { PointOfInterest } from "./poi.ts";

export const pois: PointOfInterest[] = [
  {
    "type": "chunk",
    "x": -16,
    "y": -80
  },
  {
    "type": "chunk",
    "x": -16,
    "y": -64
  },
  {
    "type": "chunk",
    "x": -16,
    "y": -48
  },
  {
    "type": "chunk",
    "x": 0,
    "y": -32
  },
  {
    "type": "chunk",
    "x": 0,
    "y": -16
  },
  {
    "type": "chunk",
    "x": 16,
    "y": -16
  },
  {
    "type": "chunk",
    "x": 16,
    "y": 0
  },
  {
    "type": "chunk",
    "x": 16,
    "y": 32
  },
  {
    "type": "chunk",
    "x": 49,
    "y": -6
  },
  {
    "type": "chunk",
    "x": 16,
    "y": -32
  },
  {
    "type": "chunk",
    "x": 32,
    "y": -32
  },
  {
    "type": "chunk",
    "x": 48,
    "y": -32
  },
  {
    "type": "chunk",
    "x": 65,
    "y": -32
  },
  {
    "type": "chunk",
    "x": 65,
    "y": -48
  },
  {
    "type": "chunk",
    "x": 65,
    "y": -64
  },
  {
    "type": "chunk",
    "x": 65,
    "y": -80
  },
  {
    "type": "chunk",
    "x": 65,
    "y": -16
  },
  {
    "type": "chunk",
    "x": 65,
    "y": 0
  },
  {
    "type": "chunk",
    "x": 49,
    "y": 0
  },
  {
    "type": "chunk",
    "x": 32,
    "y": -16
  },
  {
    "type": "chunk",
    "x": 49,
    "y": -16
  },
  {
    "title": "Farm à PDT",
    "description": "On n'en récolte un peu pour les autres et on replante.",
    "x1": 323,
    "y1": 76,
    "x2": 399,
    "y2": 32,
    "color": "green"
  },
  {
    "title": "Outils pour démarrer",
    "color": "gray",
    "type": "startup",
    "x": 12,
    "y": 26
  },
  {
    "title": "Ferme à Bonemeal",
    "color": "gray",
    "type": "startup",
    "x": -3,
    "y": 12
  },
  {
    "title": "Stock à Bonemeal",
    "color": "gray",
    "type": "startup",
    "x": 31,
    "y": -9
  },
  {
    "title": "Spawn",
    "color": "purple",
    "type": "startup",
    "x": 1,
    "y": 3
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 0,
    "y": -48
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 0,
    "y": -64
  },
  {
    "title": "chunk",
    "type": "chunk",
    "x": 16,
    "y": -48
  }
];
